export const SET_TEMPLATE = 'SET_TEMPLATE'

/* POPUP TYPES */
export const OPEN_POPUP = 'OPEN_POPUP'
export const CLOSE_POPUP = 'CLOSE_POPUP'

/* CART TYPES */
export const ADD_TO_PRODUCT = 'ADD_TO_PRODUCT'
export const REMOVE_FROM_PRODUCT = 'REMOVE_FROM_PRODUCT'
export const INCREASE_PRODUCT = 'INCREASE_PRODUCT'
export const DECREASE_PRODUCT = 'DECREASE_PRODUCT'

/* CATEGORIES TYPES */
export const SET_CATEGORIES = 'SET_CATEGORIES'