export const SET_TEMPLATE = 'SET_TEMPLATE'

/* POPUP TYPES */
export const OPEN_POPUP = 'OPEN_POPUP'
export const CLOSE_POPUP = 'CLOSE_POPUP'

/* CART TYPES */
export const UPDATE_CART = 'UPDATE_CART'
export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'
export const INCREASE_PRODUCT_COUNT = 'INCREASE_PRODUCT_COUNT'
export const DECREASE_PRODUCT_COUNT = 'DECREASE_PRODUCT_COUNT'
export const CHANGE_PRODUCT_COUNT = 'CHANGE_PRODUCT_COUNT'

/* FAVORITE TYPES */
export const UPDATE_FAVORITES = 'UPDATE_FAVORITES'
export const ADD_TO_FAVORITES = 'ADD_TO_FAVORITES'
export const REMOVE_FROM_FAVORITES = 'REMOVE_FROM_FAVORITES'

/* CATEGORIES TYPES */
export const SET_CATEGORIES = 'SET_CATEGORIES'

/* USER TYPES */
export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'